# Log rotation for Telemon
/home/remcov/telemon/telemon.log {
    daily
    rotate 7
    compress
    delaycompress
    missingok
    notifempty
    create 644 remcov remcov
}

/home/remcov/telemon/telemon_cron.log {
    daily
    rotate 7
    compress
    delaycompress
    missingok
    notifempty
    create 644 remcov remcov
}
